fragment BlogParts on Blog {
  __typename
  title
  date
  author
  excerpt
  categories
  image
  body
}

fragment EventParts on Event {
  __typename
  title
  date
  endDate
  location
  category
  image
  body
}
